### ISSUE TITLE
How can i creat the animation based on my dataset

### ISSUE THREAD

**Issue by Spatial-R** [grantbrown/episim#1]
Thanks for your example for the SEIR simulation. 
Recently, i have some spatial sites(fox example, 100 cities) and simulate the Measles dynamic among all the city using the ABSEIR package. After that, i want to create a animation wilt fixed spatial site in the map to show how the measles spread among the 100 cities.  Is there any example? Thanks.

**Comment by grantbrown** [comment]
Hmm, this isn't really a visualization of analyzed data, but a self contained simulation designed to give to illustrate SEIR dynamics. 

You might want to look into the datamaps package to see if there's anything you can use to build a more general visualization for your problem. 

Also, if you're able to make an appropriate plot in R for a single time point, you can always use a loop to plot the disease state at each time point, and then stitch them together into a video.
